export const WISHLIST_PRODUCTS_LOADING = "WISHLIST_PRODUCTS_LOADING";
export const WISHLIST_PRODUCTS_SUCCESS = "WISHLIST_PRODUCTS_SUCCESS";
export const WISHLIST_PRODUCTS_ERROR = "WISHLIST_PRODUCTS_ERROR";


